spring.application.name=Prodouct
# Server Configuration
server.port=8081

# Database Configuration (PostgreSQL)

spring.datasource.url=jdbc:postgresql://localhost:5432/OnlineShopping
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialization-mode=always
spring.datasource.schema=classpath:/schema.sql
spring.datasource.continue-on-error=true

# JPA (Hibernate) Configuration

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

